### ISSUE TITLE
How to create an environment to compile giswater?

### ISSUE THREAD

**Issue by nexusbr** [Giswater/giswater#6]
Hi David:

I want to compile the whole application. How do i create an environment to compile it? What is necessary? Is there any instructions to do that?

**Comment by daviderill** [comment]
First of all, you need a Java IDE. I would strongly recommend you to use Eclipse Luna: https://www.eclipse.org/downloads/
You need to have installed JRE 1.7
Download project source code from Github and create a New Java Project with it. Remember that source folders are 'src' and 'i18n'
Add to project classpath all libraries located inside 'lib' folder
Try to Build the project. It will generate compiled class files inside 'bin' folder
Try to Run the project
Try to Create runnable jar file executing 'create_runnable_jar.xml', using Ant buid tool

**Comment by daviderill** [comment]
As you can see, I've just made a commit adding an Ant build file that people can use to create runnable jar file. Also different epanet and epaswmm executable files.
