### ISSUE TITLE
GISWater database dictionary

### ISSUE THREAD

**Issue by nexusbr** [Giswater/giswater#7]
Hi David:

Were do i find the GISWater database dictionary?

Thanks,

**Comment by daviderill** [comment]
Prezado Jose Maria,
First of all, let me say thanks for your interest in Giswater.
We are working in order to make Giswater an Open software project and also a collaborative project. Unfortunately, we are not 100% ready yet. For example, we have not documented the database structure yet.

**Comment by gubuntu** [comment]
Has this been done since the OP? If so please post the url

**Comment by xtorret** [comment]
Hi Gavin,
Datamodel dictionary is on https://github.com/Giswater/giswater_dbmodel/wiki/Dbmodel-main-issues
You can navigate through keys and subkeys. You will find lots of info there (much more than main issues)
Anyway, if you find some doubt, feel free to write specific request
Thank you for your confidence!
