### ISSUE TITLE
More of a question than an issue...

### ISSUE THREAD

**Issue by tveinot** [Giswater/giswater#74]
Will GIS Water be moved to QGIS3 or have a QGIS3 compatibility version? I am just curious if that is something being planned or something that will be addressed in another development like giswater4.

**Comment by xtorret** [comment]
Hello.
Thank you for your question. Code migration from QGIS2 to QGIS3 is finishing:
https://github.com/Giswater/giswater_qgis_plugin/issues/529
You can test using branch dev-3.2. Next 30/05/2019 is deadline to release first stable version
There are no plans to upgrade to Giswater4.

**Comment by tveinot** [comment]
Good to hear, I will certainly have a look at the dev.
